{{- if and .Values.global.ericIngress.enabled .Values.global.ip_version (or (eq .Values.global.ip_version "Dual") (eq .Values.global.ip_version "IPv6_EXT")) }}
apiVersion: routing.ericingress.ericsson.com/v1alpha1
kind: EricIngress
metadata:
  name: eric-enmsg-custom-fm-oneflow-ipv6
spec:
  virtualServiceIP: {{ .Values.global.vips.svc_FM_vip_ipv6address }}
  backends:
    name: eric-enmsg-custom-fm-oneflow-ipv6
    config:
      - ports:
          vipPort: 162
          svcPort: 162
        protocol: udp
        algo: rr
        mode: nat
{{- end }}